### ISSUE TITLE
Move all settings into one menu item "Settings"

### ISSUE THREAD

**Issue by tanius** [edgeryders/discourse-annotator#132]
Currently, there are two menu items containing settings "User Settings" and "Languages". And we'll have more in the near future. So let's better move them into a menu item "Settings" that has sub-menu items which only appear when clicking it:

* Settings
    * Languages
    * Language Preferences

Also please provide a vertical gap between the first menu items and the "Settings" menu item that comes last.

**Comment by damingo** [comment]
Will be released with the next version.
