### ISSUE TITLE
Provide better formatting of the annotations list

### ISSUE THREAD

**Issue by tanius** [edgeryders/discourse-annotator#134]
Currently, the [list of annotations](https://edgeryders.eu/annotator/annotations) has several issues that make it hard to navigate and should be fixed:

* **The code name uses non-breaking whitespace.** Consequently, for long code names, this column will use up most of the screen width because codenames do not break into multiple lines. A horizontal scrollbar will then appear, making the list hard to navigate. This is a CSS issue.

* **The quote column is too narrow.** The quote column will typically be the widest one, and thus should be assigned a minimum of 35-40% of the available table width. Code names can also be long, but most will take only one line, so having to read a few with linebreaks is not a big issue. While linebreaks every 25 characters in the quote column makes it hard to read and makes the whole table very long and contain a lot of unused space in the other columns, so it should be fixed.

* **The quote column contains too much text.** Quotes can occasionally be long texts, and in these cases should be shown using the first 200 characters, then "[…]", then the last 200 characters.

**Comment by damingo** [comment]
Done.
