### ISSUE TITLE
Support exporting code lists to HTML

### ISSUE THREAD

**Issue by tanius** [edgeryders/discourse-annotator#136]
Ethnographers would like to have a way to copy a list of codes (incl. the hierarchy information) to their codebook document. Right now they write the codebook with a word processor, but that will change eventually (see #119). The export-to-HTML feature should also serve us later as the basis for creating a whole codebook from this software.

A page with simple (!) HTML, opening in a new browser tab, seems to be the most suitable format. It can be copy&pasted into most word processors without losing formatting, and when using just basic HTML tags there will also not be any extra formatting information that has to be removed in the word processor. On the other hand, it would be harder to import a Markdown document properly into (say) Google Docs.

The export option should be accessible with an "Export current list" button in the top right of the [list of codes](https://edgeryders.eu/annotator/codes). Due to the way we use Discourse tags to mark coding projects, this export feature needs to be implemented in conjunction with adding a Discourse tag filter (#135).

The export should use the following formatting:

* one list item of an UL list per code
* using sub-levels in the list to show the nesting of codes in the hierarchy, equivalent to how the [codes list](https://edgeryders.eu/annotator/codes) shows the hierarchy right now
* the code name in bold, followed by a dot
* the code description, after the code name

Example:

> * **Code name 1.** This is the description of the code with code name 1.
> 
>     It may have multiple paragraphs, represented by empty lines in the description field.
> 
>     * **Sub-code name 1.1.** This is the description of the first code nested below the code with code name 1.
> 
>     * **Sub-code name 1.2.** This is the description of the second code nested below the code with code name 1. There could be any number of nesting levels in the hierarchy, but we show only one here.
> 
> * **Code name 2.** This is the description of the code with code name 2.

**Comment by damingo** [comment]
This is now implemented as `View: Plain List`  which can be selected at the top-right in the [codes list](https://edgeryders.eu/annotator/codes). 

The displayed list is paginated. This is required as due to multi-language support the creation of the list is expensive and without pagination thousands of codes could be included.
