### ISSUE TITLE
Used codes in the right-side bar are no longer clickable

### ISSUE THREAD

**Issue by albertocottica** [edgeryders/discourse-annotator#225]
The POPREBEL ethnographers report that the "Used codes", visualized in the vertical bar to the right of the coded text in the coding view, is no longer clickable. Clicking used to highlight the snippet(s) associated to that particular code. 

![image](https://user-images.githubusercontent.com/1976806/152560488-73bdbccb-00f5-4765-95c6-d3d502f26403.png)

**Comment by albertocottica** [comment]
Wonderful! @damingo, do you have a timeline for that?

**Comment by damingo** [comment]
Right now working on https://github.com/edgeryders/discourse-annotator/issues/6. This issue is next - should both be done by the end of next week.

**Comment by damingo** [comment]
Done. Clicking codes in the sidebar now highlights the annotated text.
