### ISSUE TITLE
`annotations` endpoint returns 500 error message

### ISSUE THREAD

**Issue by albertocottica** [edgeryders/discourse-annotator#227]
If I point my browser to https://edgeryders.eu/annotator/annotations, everything works. But if I try to use the API endpoint for Tulip, I get an error. Even with the browser, when it's guaranteed I am not making any mistake passing the API key to Discourse: https://edgeryders.eu/annotator/annotations.json returns 
```
status: 500
error : "Internal Server Error"
```
Other endpoints seem to work. For example, `https://edgeryders.eu/annotator/codes.json`,  `https://edgeryders.eu/admin/consent.json`. 

What can I do to gain access back? @tanius, @damingo, can I have a little help?

**Comment by damingo** [comment]
Sorry, my mistake. I forgot to rename a variable when `tags` were renamed to `codes` some time ago. Now fixed.

**Comment by albertocottica** [comment]
Thanks Daniel, it works perfectly now.
