### ISSUE TITLE
a 404 error is returned after bulk destroying annotations

### ISSUE THREAD

**Issue by albertocottica** [edgeryders/discourse-annotator#232]
The bulk destroy function still works, however. See: 

https://edgeryders.eu/t/delivering-the-codebook/16970/11?u=alberto

**Comment by damingo** [comment]
Hmm... unable to reproduce this. I selected two (test) annotations, click on `Delete selected` and I'm redirected back to the same page with a notification `2 annotations were destroyed.`.

**Comment by albertocottica** [comment]
Ok, then let's close it, it was never a big deal anyway.
