### ISSUE TITLE
Make Open Ethnographer annotations refer to post revisions

### ISSUE THREAD

**Issue by tanius** [edgeryders/discourse-annotator#6]
Currently, Open Ethnographer annotations refer to posts, by post ID ([example](https://github.com/edgeryders/discourse/issues/97#issuecomment-339451373)).

This creates problems when the post is edited after the annotation has been created. Namely, the XPath anchoring mechanism to refer to the first and last word of an annotation's quote text may not be able to anchor the XPath expressions to the new version of the post. This can usually be fixed by trying to find the quote text in the new version of the post, but that is not guaranteed to succeed and may need manual intervention (as [we experienced](https://github.com/edgeryders/discourse/issues/90#issuecomment-328684878)).

This issue only happens rarely, as coding happens usually weeks after posts have been written, and post are usually not edited by their original authors then anymore. However, to have a well thought-through architecture, it makes sense to solve this in the medium term.

For that, Open Ethnographer annotations would also refer to a specific revision and not only to a specific post. Since revisions cannot be deleted in Discourse (they can only be "hidden" but admins can still see them), that is a robust approach.

**Comment by damingo** [comment]
Done. If a post is now edited after it was annotated all annotations will refer to the revision prior to the edit.
