### ISSUE TITLE
Rename this repository to discourse-annotator

### ISSUE THREAD

**Issue by tanius** [edgeryders/discourse-annotator#96]
The current name of this repository `annotator_store-gem` is no longer suitable: it is just the name of the base repository we forked and then extended to morph it into the Open Ethnographer software it is now. (Rationale for that: Since the original repository is unmaintained, forking it in order to create a different software out of it is "ok". There's nothing to win by creating a fresh, empty repository that then depends on the original `annotator_store-gem` as a gem library: since the original repo is unmaintained, no updates will come in from that gem.)

Anyway, we need a new name. Currently the best proposal is `discourse-annotator`. That suits the new direction of development that I propose for this project (see #75). Beyond the reference to the Discourse software and to the Annotator.JS software it relies on, that name has its own meaning of "annotation software for online discussions", which is exactly what it does so far.

(Another name that made it to the final selection is `discourse-analyzer`. All the reasons for `discourse-annotator` apply as well, except that it does not reference Annotator.JS. This name would be the best if and when this software is merged with Graphryder into one. Because then it would no longer be just about annotating but also analyzing Discourse content. However, we do not know if we'll ever merge it with Graphryder. If we do, we might rename the software again.)

**Comment by damingo** [comment]
Done.
